# Generated by Django 5.0.7 on 2024-07-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Flow_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCollaborator',
            new_name='ProjectCollaboration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='collaborations',
            field=models.ManyToManyField(blank=True, related_name='collaborators', through='Work_Flow_App.ProjectCollaboration', to='Work_Flow_App.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='owned_projects',
            field=models.ManyToManyField(blank=True, related_name='owners', to='Work_Flow_App.project'),
        ),
    ]
