# Generated by Django 5.0.7 on 2024-07-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Flow_App', '0004_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
    ]
