# Generated by Django 5.0.7 on 2024-07-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Flow_App', '0005_remove_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background_image',
            field=models.CharField(blank=True, default='../src/assets/defaultBackground.jpg', max_length=200, null=True),
        ),
    ]
